# -*- coding: utf-8 -*-
"""Filejoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SB32lt8E4gHsDcXaIBgBHRhuLr2oq1Dh
"""

import pandas as pd

from google.colab import files
uploaded=files.upload()

df1=pd.read_excel('file_3.xlsx')

df1 = df1.dropna(axis=0, how='all')

df1 = df1.dropna(axis=1, how='all')

df1=df1.fillna('')
df1

header_row_index = 2
new_header = df1.iloc[header_row_index]       # get the header row
df1 = df1.iloc[header_row_index + 1:]          # keep the data below it
df1.columns = new_header                      # set new header
df1 = df1.reset_index(drop=True)
df1.columns = df1.columns.str.replace('\n', ' ', regex=True)

for x in df1.index:
    if df1.loc[x, "Unit of measure"] == '':
        df1.drop(x, inplace=True)

df1

df2=pd.read_excel('file_2.xlsx')

df2=df2.dropna(axis=0, how='all')

df2=df2.dropna(axis=1, how='all')

df2=df2.fillna('')
df2

header_row_index = 2
new_header = df2.iloc[header_row_index]       # get the header row
df2 = df2.iloc[header_row_index + 1:]          # keep the data below it
df2.columns = new_header                      # set new header
df2 = df2.reset_index(drop=True)
df2.columns = df2.columns.str.replace('\n', ' ', regex=True)

for x in df2.index:
    if df2.loc[x, "Unit of measure"] == '':
        df2.drop(x, inplace=True)

df2

df3=pd.read_excel('file_3.xlsx')

df3=df3.dropna(axis=0, how='all')

df3=df3.dropna(axis=1, how='all')

df3=df3.fillna('')
df3

new_header = df3.iloc[header_row_index]       # get the header row
df3 = df3.iloc[header_row_index + 1:]          # keep the data below it
df3.columns = new_header                      # set new header
df3 = df3.reset_index(drop=True)
df3.columns = df3.columns.str.replace('\n', ' ', regex=True)

for x in df3.index:
    if df3.loc[x, "Unit of measure"] == '':
        df3.drop(x, inplace=True)

df3

Data_Cleaning=pd.concat([df1, df2, df3], ignore_index=True)

Data_Cleaning

Data_Cleaning['Sr. no.'] = range(1, len(Data_Cleaning) + 1)
Data_Cleaning

backup_df = Data_Cleaning.copy()

Data_Cleaning.to_excel("Data_Cleaning.xlsx", index=False)

files.download("Data_Cleaning.xlsx")

import zipfile
import os

dataframes = {
    "df1": df1,
    "df2": df2,
    "df3": df3
}

for name, dataframe in dataframes.items():
    dataframe.to_excel(f"{name}.xlsx", index=False)

with zipfile.ZipFile("all_dataframes.zip", "w") as zipf:
    for name in dataframes.keys():
        filename = f"{name}.xlsx"
        zipf.write(filename)

files.download("all_dataframes.zip")